# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'
platform :ios, '11.2'
#use_frameworks!

target 'filmhouseMobile' do
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', 
    'RCTActionSheet',
    'CxxBridge',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Brightcove-Player-Core'

  # pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  pod 'boost-for-react-native', :podspec => 'https://raw.githubusercontent.com/react-native-community/boost-for-react-native/master/boost-for-react-native.podspec'
  #pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-paystack', :path => '../node_modules/react-native-paystack'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  post_install do |installer|
    installer.pods_project.targets.each do |target|

      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

    end
  end

end
