/**Films */

export const SAVE_LANDING_FILMS = "SAVE_LANDING_FILMS";
export const SAVE_HEROE_BANNER = "SAVE_HEROE_BANNER";
export const SAVE_CURRENTLY_SHOWING = "SAVE_CURRENTLY_SHOWING";
export const SAVE_UPCOMING_FILMS = "SAVE_UPCOMING_FILMS";
export const SAVE_VOD_FILMS = "SAVE_VOD_FILMS";
export const SAVE_SVOD_FILMS = "SAVE_SVOD_FILMS";
export const SAVE_FEATURED_CINEMA_FILM = "SAVE_FEATURED_CINEMA_FILM";
export const SAVE_FILM_ONE = "SAVE_FILM_ONE";
export const SAVE_CINEMA_STATE = "SAVE_CINEMA_STATE";
export const SAVE_CINEMA_STATE_ID = "SAVE_CINEMA_STATE_ID";
export const SAVE_CINEMA_STATE_NAME = "SAVE_CINEMA_STATE_NAME";
export const SAVE_SHOW_TIME = "SAVE_SHOW_TIME";
export const SAVE_ACTIVE_MOVIE = "SAVE_ACTIVE_MOVIE";
export const CLEAR_PREV_SHOW_TIME = "CLEAR_PREV_SHOW_TIME";
export const SAVE_DATE_RANGE = "SAVE_DATE_RANGE";
export const SAVE_FILM_GENRE = "SAVE_FILM_GENRE";
/**Concessions */

export const SAVE_CONCESSION_ITEMS = "SAVE_CONCESSION_ITEMS";
export const SAVE_MERCHANDISE_ITEMS = "SAVE_MERCHANDISE_ITEMS";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_CART_ITEMS = "CLEAR_SHOP_ITEMS";
export const REPLACE_ITEM_IN_CART = "REPLACE_ITEM_IN_CART";
export const SAVE_ITEMS_COUNT = "SAVE_ITEMS_COUNT";
export const TOTAL_PRICE = "TOTAL_PRICE";
export const REPLACE_CHECKOUT_ITEMS = "REPLACE_CHECKOUT_ITEMS";
export const SAVE_PAYMENT_REF = "SAVE_PAYMENT_REF";
/**Loaders */

export const LOADER_START = "LOADER_START";
export const ITEM_LOADER_STOP = "ITEM_LOADER_STOP";
export const ITEM_LOADER_START = "ITEM_LOADER_START";
export const LOADER_STOP = "LOADER_STOP";
export const ALERT_MESSAGE = "ALERT_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

/**Auth Actions */

export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_GUEST_USER = "SAVE_GUEST_USER";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const SAVE_USER_PLAYLIST = "SAVE_USER_PLAYLIST";
export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN";
/**Ticket section */
export const ADD_TICKET_ITEM_TO_CART = "ADD_TICKET_ITEM_TO_CART";
export const REPLACE_TICKET_ITEM_TO_CART = "REPLACE_TICKET_ITEM_TO_CART";
export const SAVE_TICKET_TYPE = "SAVE_TICKET_TYPE";
export const SAVE_TRANSACTION_ID = "SAVE_TRANSACTION_ID";
export const TOTAL_TICKET_PRICE = "TOTAL_TICKET_PRICE";
export const CLEAR_TICKET_CONCESSION_CHECKOUT =
  "CLEAR_TICKET_CONCESSION_CHECKOUT";
export const REMOVE_ITEM_PRICE = "REMOVE_ITEM_PRICE";
export const CLEAR_TICKET_PRICE = "CLEAR_TICKET_PRICE";
export const SAVE_ACTIVE_USER = "SAVE_ACTIVE_USER";
export const CLEAR_TICKET_CHECKOUT = "CLEAR_TICKET_CHECKOUT";
export const SAVE_GUEST_LIST = "SAVE_GUEST_LIST";
export const SAVE_TICKET_PAYMENT_REF = "SAVE_TICKET_PAYMENT_REF";
export const ADD_TICKET_CONCESSION_ITEM_TO_CART =
  "ADD_TICKET_CONCESSION_ITEM_TO_CART";
export const REPLACE_TICKET_CONCESSION_ITEM_IN_CART =
  "REPLACE_TICKET_CONCESSION_ITEM_IN_CART";
export const TOTAL_TICKET_CONCESSION_PRICE = "TOTAL_TICKET_CONCESSION_PRICE";
export const SAVE_TICKET_CONCESSION_ID = "SAVE_TICKET_CONCESSION_ID";
export const SAVE_COUNTDOWN_TIMER = "SAVE_COUNTDOWN_TIMER";
export const TIMER_EXPIRED = "TIMER_EXPIRED";
